In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("long_data_.csv")

In [3]:
df.columns

Index(['States', 'Regions', 'latitude', 'longitude', 'Dates', 'Usage'], dtype='object')

In [4]:
df

          States Regions   latitude  longitude                Dates  Usage
0         Punjab      NR  31.519974  75.980003  02/01/2019 00:00:00  119.9
1        Haryana      NR  28.450006  77.019991  02/01/2019 00:00:00  130.3
2      Rajasthan      NR  26.449999  74.639981  02/01/2019 00:00:00  234.1
3          Delhi      NR  28.669993  77.230004  02/01/2019 00:00:00   85.8
4             UP      NR  27.599981  78.050006  02/01/2019 00:00:00  313.9
...          ...     ...        ...        ...                  ...    ...
16594    Manipur     NER  24.799971  93.950017  05/12/2020 00:00:00    2.5
16595  Meghalaya     NER  25.570492  91.880014  05/12/2020 00:00:00    5.8
16596    Mizoram     NER  23.710399  92.720015  05/12/2020 00:00:00    1.6
16597   Nagaland     NER  25.666998  94.116570  05/12/2020 00:00:00    2.1
16598    Tripura     NER  23.835404  91.279999  05/12/2020 00:00:00    3.3

[16599 rows x 6 columns]

In [5]:
for i,row in df.iterrows():
    string=row['Dates'].replace(' 00:00:00','')
    df['Dates'][i]=string

a:\projects\electricity consumption datathon\ecd\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [6]:
df

          States Regions   latitude  longitude       Dates  Usage
0         Punjab      NR  31.519974  75.980003  02/01/2019  119.9
1        Haryana      NR  28.450006  77.019991  02/01/2019  130.3
2      Rajasthan      NR  26.449999  74.639981  02/01/2019  234.1
3          Delhi      NR  28.669993  77.230004  02/01/2019   85.8
4             UP      NR  27.599981  78.050006  02/01/2019  313.9
...          ...     ...        ...        ...         ...    ...
16594    Manipur     NER  24.799971  93.950017  05/12/2020    2.5
16595  Meghalaya     NER  25.570492  91.880014  05/12/2020    5.8
16596    Mizoram     NER  23.710399  92.720015  05/12/2020    1.6
16597   Nagaland     NER  25.666998  94.116570  05/12/2020    2.1
16598    Tripura     NER  23.835404  91.279999  05/12/2020    3.3

[16599 rows x 6 columns]

In [7]:
df=df[df['Regions']=='NR']

In [8]:
df

            States Regions   latitude  longitude       Dates  Usage
0           Punjab      NR  31.519974  75.980003  02/01/2019  119.9
1          Haryana      NR  28.450006  77.019991  02/01/2019  130.3
2        Rajasthan      NR  26.449999  74.639981  02/01/2019  234.1
3            Delhi      NR  28.669993  77.230004  02/01/2019   85.8
4               UP      NR  27.599981  78.050006  02/01/2019  313.9
...            ...     ...        ...        ...         ...    ...
16570           UP      NR  27.599981  78.050006  05/12/2020  287.3
16571  Uttarakhand      NR  30.320409  78.050006  05/12/2020   35.2
16572           HP      NR  31.100025  77.166597  05/12/2020   24.3
16573          J&K      NR  33.450000  76.240000  05/12/2020   42.6
16574   Chandigarh      NR  30.719997  76.780006  05/12/2020    3.5

[4527 rows x 6 columns]

In [9]:
df['Dates']=pd.to_datetime(df['Dates'])
df['Dates'].describe()

a:\projects\electricity consumption datathon\ecd\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
a:\projects\electricity consumption datathon\ecd\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.

count                    4527
unique                    498
top       2019-11-07 00:00:00
freq                       18
first     2019-01-07 00:00:00
last      2020-05-23 00:00:00
Name: Dates, dtype: object

In [12]:
df=df[(df['Dates'] >="2019-12-01") & (df['Dates'] <= "2020-12-05")]
df

            States Regions   latitude  longitude      Dates  Usage
330         Punjab      NR  31.519974  75.980003 2019-12-01  137.9
331        Haryana      NR  28.450006  77.019991 2019-12-01  151.9
332      Rajasthan      NR  26.449999  74.639981 2019-12-01  189.9
333          Delhi      NR  28.669993  77.230004 2019-12-01   92.6
334             UP      NR  27.599981  78.050006 2019-12-01  298.6
...            ...     ...        ...        ...        ...    ...
16570           UP      NR  27.599981  78.050006 2020-05-12  287.3
16571  Uttarakhand      NR  30.320409  78.050006 2020-05-12   35.2
16572           HP      NR  31.100025  77.166597 2020-05-12   24.3
16573          J&K      NR  33.450000  76.240000 2020-05-12   42.6
16574   Chandigarh      NR  30.719997  76.780006 2020-05-12    3.5

[1584 rows x 6 columns]

In [13]:
df.loc[(df['Dates'] <="2020-03-24") & (df['Dates'] >= "2019-01-12"),'Situation']='Pre-Covid'

a:\projects\electricity consumption datathon\ecd\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
a:\projects\electricity consumption datathon\ecd\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [14]:
df.loc[(df['Dates'] >="2020-03-25") & (df['Dates'] <= "2020-12-05"),'Situation']='Covid-Lockdown'

In [17]:
df.head(35)

           States Regions   latitude  longitude      Dates  Usage  Situation
330        Punjab      NR  31.519974  75.980003 2019-12-01  137.9  Pre-Covid
331       Haryana      NR  28.450006  77.019991 2019-12-01  151.9  Pre-Covid
332     Rajasthan      NR  26.449999  74.639981 2019-12-01  189.9  Pre-Covid
333         Delhi      NR  28.669993  77.230004 2019-12-01   92.6  Pre-Covid
334            UP      NR  27.599981  78.050006 2019-12-01  298.6  Pre-Covid
335   Uttarakhand      NR  30.320409  78.050006 2019-12-01   34.7  Pre-Covid
336            HP      NR  31.100025  77.166597 2019-12-01   26.4  Pre-Covid
337           J&K      NR  33.450000  76.240000 2019-12-01   34.6  Pre-Covid
338    Chandigarh      NR  30.719997  76.780006 2019-12-01    4.0  Pre-Covid
1320       Punjab      NR  31.519974  75.980003 2019-12-02  108.5  Pre-Covid
1321      Haryana      NR  28.450006  77.019991 2019-12-02  117.4  Pre-Covid
1322    Rajasthan      NR  26.449999  74.639981 2019-12-02  205.0  Pre-Covid
1323        Delhi      NR  28.669993  77.230004 2019-12-02   64.8  Pre-Covid
1324           UP      NR  27.599981  78.050006 2019-12-02  281.4  Pre-Covid
1325  Uttarakhand      NR  30.320409  78.050006 2019-12-02   33.2  Pre-Covid
1326           HP      NR  31.100025  77.166597 2019-12-02   26.7  Pre-Covid
1327          J&K      NR  33.450000  76.240000 2019-12-02   43.9  Pre-Covid
1328   Chandigarh      NR  30.719997  76.780006 2019-12-02    3.5  Pre-Covid
2211       Punjab      NR  31.519974  75.980003 2019-12-03  257.9  Pre-Covid
2212      Haryana      NR  28.450006  77.019991 2019-12-03  214.0  Pre-Covid
2213    Rajasthan      NR  26.449999  74.639981 2019-12-03  212.7  Pre-Covid
2214        Delhi      NR  28.669993  77.230004 2019-12-03  132.6  Pre-Covid
2215           UP      NR  27.599981  78.050006 2019-12-03  431.3  Pre-Covid
2216  Uttarakhand      NR  30.320409  78.050006 2019-12-03   44.3  Pre-Covid
2217           HP      NR  31.100025  77.166597 2019-12-03   29.8  Pre-Covid
2218          J&K      NR  33.450000  76.240000 2019-12-03   39.7  Pre-Covid
2219   Chandigarh      NR  30.719997  76.780006 2019-12-03    6.1  Pre-Covid
3201       Punjab      NR  31.519974  75.980003 2019-12-04   93.1  Pre-Covid
3202      Haryana      NR  28.450006  77.019991 2019-12-04   95.0  Pre-Covid
3203    Rajasthan      NR  26.449999  74.639981 2019-12-04  212.0  Pre-Covid
3204        Delhi      NR  28.669993  77.230004 2019-12-04   60.2  Pre-Covid
3205           UP      NR  27.599981  78.050006 2019-12-04  230.0  Pre-Covid
3206  Uttarakhand      NR  30.320409  78.050006 2019-12-04   31.7  Pre-Covid
3207           HP      NR  31.100025  77.166597 2019-12-04   26.9  Pre-Covid
3208          J&K      NR  33.450000  76.240000 2019-12-04   46.0  Pre-Covid

In [18]:
def getSeason(date,index):
    month = int(str(date).replace(" 00:00:00",'').split("-")[1])
    if (month > 11 or month <= 3):
        df['Season'][index]="WINTER"
    elif (month == 4 or month == 5):
        df['Season'][index]="SPRING"
    elif (month >=6 and month <= 9):
        df['Season'][index]="SUMMER"
    else:
        df['Season'][index]="FALL"

In [19]:
df['Season']=None
for i,row in df.iterrows():
    getSeason(row['Dates'],i)

a:\projects\electricity consumption datathon\ecd\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
a:\projects\electricity consumption datathon\ecd\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
a:\projects\electricity consumption datathon\ecd\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
a:\projects\electricity consumption datathon\ecd\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [20]:
df

,States,Regions,latitude,longitude,Dates,Usage,Situation,Season
330,Punjab,NR,31.519974,75.980003,2019-12-01,137.9,Pre-Covid,WINTER
331,Haryana,NR,28.450006,77.019991,2019-12-01,151.9,Pre-Covid,WINTER
332,Rajasthan,NR,26.449999,74.639981,2019-12-01,189.9,Pre-Covid,WINTER
333,Delhi,NR,28.669993,77.230004,2019-12-01,92.6,Pre-Covid,WINTER
334,UP,NR,27.599981,78.050006,2019-12-01,298.6,Pre-Covid,WINTER
...,...,...,...,...,...,...,...,...
16570,UP,NR,27.599981,78.050006,2020-05-12,287.3,Covid-Lockdown,SPRING
16571,Uttarakhand,NR,30.320409,78.050006,2020-05-12,35.2,Covid-Lockdown,SPRING
16572,HP,NR,31.100025,77.166597,2020-05-12,24.3,Covid-Lockdown,SPRING
16573,J&K,NR,33.450000,76.240000,2020-05-12,42.6,Covid-Lockdown,SPRING
16574,Chandigarh,NR,30.719997,76.780006,2020-05-12,3.5,Covid-Lockdown,SPRING

In [21]:
df.to_csv("ECDataset.csv",index=False)